// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThinkBridge_ERP.Data;

#nullable disable

namespace ThinkBridge_ERP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227154018_UpdateSubscriptionPlans")]
    partial class UpdateSubscriptionPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.CalendarEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EventID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectID");

                    b.ToTable("CalendarEvent");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.ChangeRequest", b =>
                {
                    b.Property<int>("CRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CRID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CRID");

                    b.HasIndex("ProductID");

                    b.HasIndex("RequestedBy");

                    b.ToTable("ChangeRequest");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CompanyID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FolderID")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CompanyID");

                    b.HasIndex("FolderID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.DocumentAccess", b =>
                {
                    b.Property<int>("DocAccessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocAccessID"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("DocAccessID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("RoleID");

                    b.ToTable("DocumentAccess");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.DocumentTag", b =>
                {
                    b.Property<int>("DocTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocTagID"));

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("DocTagID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("TagID");

                    b.ToTable("DocumentTag");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.DocumentVersion", b =>
                {
                    b.Property<int>("DocVersionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocVersionID"));

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DocVersionID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("UploadedBy");

                    b.ToTable("DocumentVersion");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Folder", b =>
                {
                    b.Property<int>("FolderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FolderID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ParentFolderID")
                        .HasColumnType("int");

                    b.HasKey("FolderID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ParentFolderID");

                    b.ToTable("Folder");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubscriptionID")
                        .HasColumnType("int");

                    b.HasKey("InvoiceID");

                    b.HasIndex("SubscriptionID");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.LifecycleStage", b =>
                {
                    b.Property<int>("StageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageID"));

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StageOrder")
                        .HasColumnType("int");

                    b.HasKey("StageID");

                    b.ToTable("LifecycleStage");

                    b.HasData(
                        new
                        {
                            StageID = 1,
                            StageName = "Concept",
                            StageOrder = 1
                        },
                        new
                        {
                            StageID = 2,
                            StageName = "Design",
                            StageOrder = 2
                        },
                        new
                        {
                            StageID = 3,
                            StageName = "Development",
                            StageOrder = 3
                        },
                        new
                        {
                            StageID = 4,
                            StageName = "Testing",
                            StageOrder = 4
                        },
                        new
                        {
                            StageID = 5,
                            StageName = "Production",
                            StageOrder = 5
                        });
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Module", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModuleID");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotifType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CheckoutSessionID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ExternalTransactionID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubscriptionID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("SubscriptionID");

                    b.ToTable("PaymentTransaction");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ModuleID")
                        .HasColumnType("int");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("PermissionID");

                    b.HasIndex("ModuleID");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("PostID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectID");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.PostDocument", b =>
                {
                    b.Property<int>("PostDocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostDocID"));

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.HasKey("PostDocID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("PostID");

                    b.ToTable("PostDocument");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProductID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.ProductHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("ProductID");

                    b.HasIndex("StageID");

                    b.ToTable("ProductHistory");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.ProductVersion", b =>
                {
                    b.Property<int>("VersionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionID"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("VersionID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductVersion");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Progress")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProjectID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.ProjectMember", b =>
                {
                    b.Property<int>("ProjectMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectMemberID"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberRole")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProjectMemberID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UserID");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Description = "Platform administrator with full access",
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            RoleID = 2,
                            Description = "Company administrator with full company access",
                            RoleName = "CompanyAdmin"
                        },
                        new
                        {
                            RoleID = 3,
                            Description = "Manages projects and team members",
                            RoleName = "ProjectManager"
                        },
                        new
                        {
                            RoleID = 4,
                            Description = "Regular team member",
                            RoleName = "TeamMember"
                        });
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionID"));

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SubscriptionID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("PlanID");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxProjects")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("PlanID");

                    b.ToTable("SubscriptionPlan");

                    b.HasData(
                        new
                        {
                            PlanID = 1,
                            BillingCycle = "Monthly",
                            IsActive = false,
                            MaxProjects = 3,
                            MaxUsers = 5,
                            PlanName = "Trial",
                            Price = 0.00m
                        },
                        new
                        {
                            PlanID = 2,
                            BillingCycle = "Monthly",
                            IsActive = true,
                            MaxProjects = 100,
                            MaxUsers = 35,
                            PlanName = "Starter",
                            Price = 999.00m
                        },
                        new
                        {
                            PlanID = 3,
                            BillingCycle = "Monthly",
                            IsActive = true,
                            MaxProjects = 500,
                            MaxUsers = 75,
                            PlanName = "Professional",
                            Price = 2499.00m
                        },
                        new
                        {
                            PlanID = 4,
                            BillingCycle = "Monthly",
                            IsActive = true,
                            PlanName = "Enterprise",
                            Price = 4999.00m
                        });
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.SystemSetting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingID");

                    b.HasIndex("CompanyID");

                    b.ToTable("SystemSetting");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("TagID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Priority")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TaskID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectID");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.TaskAssignment", b =>
                {
                    b.Property<int>("TaskAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskAssignmentID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TaskAssignmentID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("TaskAssignment");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.TaskUpdate", b =>
                {
                    b.Property<int>("UpdateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<string>("UpdateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UpdateID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("TaskUpdate");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Email");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@thinkbridge.com",
                            Fname = "Super",
                            IsSuperAdmin = true,
                            Lname = "Admin",
                            MustChangePassword = false,
                            Password = "$2a$11$HAUg98czHouH.kt4CQcZbOE2GFiwGVnZF0gMv2GVY5lokSKReiDUy",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserRoleID = 1,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleID = 1,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.CalendarEvent", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Creator")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Project", "Project")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Creator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.ChangeRequest", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Product", "Product")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Requester")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Comment", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Document", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Approver")
                        .WithMany("ApprovedDocuments")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Documents")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Folder", "Folder")
                        .WithMany("Documents")
                        .HasForeignKey("FolderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Uploader")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Company");

                    b.Navigation("Folder");

                    b.Navigation("Project");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.DocumentAccess", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Document", "Document")
                        .WithMany("DocumentAccesses")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Role", "Role")
                        .WithMany("DocumentAccesses")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.DocumentTag", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Document", "Document")
                        .WithMany("DocumentTags")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Tag", "Tag")
                        .WithMany("DocumentTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.DocumentVersion", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Document", "Document")
                        .WithMany("DocumentVersions")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Uploader")
                        .WithMany("DocumentVersions")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Folder", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Folders")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Invoice", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Subscription", "Subscription")
                        .WithMany("Invoices")
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Notification", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Invoice", "Invoice")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("InvoiceID");

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Subscription", "Subscription")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Permission", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Post", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Posts")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Project", "Project")
                        .WithMany("Posts")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Creator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.PostDocument", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Document", "Document")
                        .WithMany("PostDocuments")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Post", "Post")
                        .WithMany("PostDocuments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Product", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Project", "Project")
                        .WithMany("Products")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.ProductHistory", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "User")
                        .WithMany("ProductHistories")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Product", "Product")
                        .WithMany("ProductHistories")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.LifecycleStage", "Stage")
                        .WithMany("ProductHistories")
                        .HasForeignKey("StageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Stage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.ProductVersion", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Product", "Product")
                        .WithMany("ProductVersions")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Project", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Creator")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.ProjectMember", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Report", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Reports")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Creator")
                        .WithMany("Reports")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Subscription", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.SystemSetting", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("SystemSettings")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Tag", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Tags")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Task", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "Creator")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.TaskAssignment", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Task", "Task")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "User")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.TaskUpdate", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Task", "Task")
                        .WithMany("TaskUpdates")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "User")
                        .WithMany("TaskUpdates")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.User", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.UserRole", b =>
                {
                    b.HasOne("ThinkBridge_ERP.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkBridge_ERP.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Company", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CalendarEvents");

                    b.Navigation("Documents");

                    b.Navigation("Folders");

                    b.Navigation("Posts");

                    b.Navigation("Products");

                    b.Navigation("Projects");

                    b.Navigation("Reports");

                    b.Navigation("Subscriptions");

                    b.Navigation("SystemSettings");

                    b.Navigation("Tags");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Document", b =>
                {
                    b.Navigation("DocumentAccesses");

                    b.Navigation("DocumentTags");

                    b.Navigation("DocumentVersions");

                    b.Navigation("PostDocuments");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Folder", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Invoice", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.LifecycleStage", b =>
                {
                    b.Navigation("ProductHistories");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Module", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostDocuments");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Product", b =>
                {
                    b.Navigation("ChangeRequests");

                    b.Navigation("ProductHistories");

                    b.Navigation("ProductVersions");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Project", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("Documents");

                    b.Navigation("Posts");

                    b.Navigation("Products");

                    b.Navigation("ProjectMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Role", b =>
                {
                    b.Navigation("DocumentAccesses");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Subscription", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Tag", b =>
                {
                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.Task", b =>
                {
                    b.Navigation("TaskAssignments");

                    b.Navigation("TaskUpdates");
                });

            modelBuilder.Entity("ThinkBridge_ERP.Models.Entities.User", b =>
                {
                    b.Navigation("ApprovedDocuments");

                    b.Navigation("AuditLogs");

                    b.Navigation("CalendarEvents");

                    b.Navigation("ChangeRequests");

                    b.Navigation("Comments");

                    b.Navigation("CreatedProjects");

                    b.Navigation("CreatedTasks");

                    b.Navigation("DocumentVersions");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("ProductHistories");

                    b.Navigation("ProjectMemberships");

                    b.Navigation("Reports");

                    b.Navigation("TaskAssignments");

                    b.Navigation("TaskUpdates");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
